module.exports = {
	HOTELS_SEARCH_START: 'HOTELS_SEARCH_START',
	HOTELS_SEARCH_DONE: 'HOTELS_SEARCH_DONE',
	HOTELS_SEARCH_SUCCESS: 'HOTELS_SEARCH_SUCCESS',
	HOTELS_SEARCH_FAIL: 'HOTELS_SEARCH_FAIL'
};